# Generated by Django 6.0.3 on 2026-03-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_agricultor', models.CharField(max_length=200)),
                ('rut_agricultor', models.CharField(max_length=20)),
                ('comuna', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('concurso', models.CharField(max_length=100)),
                ('nombre_operador', models.CharField(max_length=200)),
                ('rut_operador', models.CharField(max_length=20)),
                ('correo_operador', models.EmailField(max_length=254)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
