# Generated by Django 6.0.3 on 2026-03-24 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_postulacion', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('rol_avaluo', models.CharField(max_length=100)),
                ('tenencia', models.CharField(max_length=50)),
                ('superficie_total', models.FloatField()),
                ('coordenada_norte', models.FloatField()),
                ('coordenada_este', models.FloatField()),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planes.plan')),
            ],
        ),
    ]
