# Generated by Django 6.0.3 on 2026-03-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_resumenplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumenplan',
            name='coordenada_este',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumenplan',
            name='coordenada_norte',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumenplan',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='resumenplan',
            name='rol_avaluo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumenplan',
            name='superficie_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumenplan',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resumenplan',
            name='tenencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resumenplan',
            name='tipo_postulacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
