# Generated by Django 6.0.3 on 2026-03-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0003_alter_resumenplan_coordenada_este_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumenplan',
            name='huso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
