# Generated by Django 6.0.3 on 2026-03-25 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0004_resumenplan_huso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Potrero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('utm_este', models.DecimalField(decimal_places=2, max_digits=12)),
                ('utm_norte', models.DecimalField(decimal_places=2, max_digits=12)),
                ('huso', models.IntegerField(choices=[(18, '18'), (19, '19')])),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('costo_total', models.DecimalField(decimal_places=0, max_digits=12)),
                ('costo_neto', models.DecimalField(decimal_places=0, max_digits=12)),
                ('porcentaje_incentivo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('incentivo_solicitado', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potreros', to='planes.plan')),
            ],
        ),
    ]
