# Generated by Django 6.0.3 on 2026-03-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0005_potrero'),
    ]

    operations = [
        migrations.AddField(
            model_name='potrero',
            name='asesoria_plan',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='potrero',
            name='costo_analisis_suelo',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='potrero',
            name='fecha_analisis',
            field=models.DateField(blank=True, null=True),
        ),
    ]
