# Generated by Django 6.0.3 on 2026-03-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0006_potrero_asesoria_plan_potrero_costo_analisis_suelo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='potrero',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='potrero',
            name='costo_neto',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='potrero',
            name='costo_total',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='potrero',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='potrero',
            name='fecha_termino',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='potrero',
            name='porcentaje_incentivo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
