# Generated by Django 6.0.3 on 2026-03-25 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0007_alter_potrero_options_alter_potrero_costo_neto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticaPotrero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('fosforo', 'Fertilización fosforada'), ('enmienda', 'Enmiendas químicas'), ('cubierta', 'Cubiertas vegetales')], max_length=20)),
                ('subtipo_enmienda', models.CharField(blank=True, choices=[('cal', 'Enmienda calcárea'), ('potasio', 'Corrección de potasio'), ('azufre', 'Corrección de azufre')], max_length=20, null=True)),
                ('subtipo_cubierta', models.CharField(blank=True, choices=[('siembra', 'Siembra'), ('regeneracion', 'Regeneración')], max_length=20, null=True)),
                ('nivel_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('nivel_final', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('resultado', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('potrero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas', to='planes.potrero')),
            ],
        ),
    ]
