# Generated by Django 6.0.3 on 2026-03-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0008_practicapotrero'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='estado_administrativo',
            field=models.CharField(blank=True, choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='motivo_rechazo_admin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
