# Generated by Django 6.0.3 on 2026-03-26 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0009_plan_estado_administrativo_plan_motivo_rechazo_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_tecnico', models.CharField(blank=True, choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], max_length=10, null=True)),
                ('motivo_rechazo_tecnico', models.TextField(blank=True, null=True)),
                ('puntaje', models.FloatField(blank=True, null=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planes.plan')),
            ],
        ),
    ]
