# Generated by Django 6.0.3 on 2026-03-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0010_evaluaciontecnica'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicapotrero',
            name='saturacion_aluminio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ingresar % de saturación de aluminio (solo enmienda calcárea)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='practicapotrero',
            name='nivel_final',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ingresar en cmol/kg (para potasio)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='practicapotrero',
            name='nivel_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ingresar en cmol/kg (para potasio)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='practicapotrero',
            name='tipo',
            field=models.CharField(choices=[('fosforo', 'Fertilización fosforada'), ('enmienda', 'Incorporación de elementos químicos esenciales'), ('cubierta', 'Cubiertas vegetales')], max_length=20),
        ),
    ]
