# Generated by Django 6.0.3 on 2026-03-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0011_practicapotrero_saturacion_aluminio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='participacion_agricultor',
            field=models.IntegerField(blank=True, choices=[(1, 'Primera vez'), (2, 'Segunda vez'), (3, 'Tercera vez')], null=True),
        ),
    ]
