# Generated by Django 6.0.3 on 2026-03-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0012_plan_participacion_agricultor'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPostulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('veces', models.IntegerField(default=0)),
            ],
        ),
    ]
