# Generated by Django 6.0.3 on 2026-03-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0013_historialpostulacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicapotrero',
            name='subtipo_enmienda',
            field=models.CharField(blank=True, choices=[('cal', 'Enmienda calcárea'), ('azufre', 'Azufre'), ('potasio', 'Potasio')], max_length=20, null=True),
        ),
    ]
