# Generated by Django 6.0.3 on 2026-04-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0014_alter_practicapotrero_subtipo_enmienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicapotrero',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
    ]
