# Generated by Django 6.0.3 on 2026-04-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0015_practicapotrero_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='estado_reconsideracion',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('aprobado', 'Reconsiderado aprobado'), ('rechazado', 'Reconsiderado rechazado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='motivo_reconsideracion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
