# Generated by Django 6.0.3 on 2026-04-06 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0016_plan_estado_reconsideracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumenplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes.plan'),
        ),
    ]
