# Generated by Django 6.0.3 on 2026-04-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0017_alter_resumenplan_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumenplan',
            name='incentivo_practicas',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='resumenplan',
            name='incentivo_total',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evaluaciontecnica',
            name='estado_tecnico',
            field=models.CharField(blank=True, choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], max_length=10, null=True),
        ),
    ]
