# Generated by Django 6.0.3 on 2026-04-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0020_plan_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
