# Generated by Django 6.0.3 on 2026-05-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0021_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='potrero',
            name='incentivo_a',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
    ]
